
//---------------------------------------------------------------------------
#include "fstream.h"
#include "constanten.h"
//#include "dir.h"                          // getcwd

#include <iostream>


#include "main.h"
//---------------------------------------------------------------------------



//---------------------------------------------------------------------------

bool TForm1::Scrijf_XML()
{
   // NB voor XML: de DATUMS zijn omgezet van DDMMYYY -> YYYYMMDD

   ofstream of_xml;
   bool schrijven_ok = true;
   AnsiString xml_regel;
   AnsiString volledig_xml_output_path;
   AnsiString info = "";
   AnsiString inspringen_1 = "        ";
   AnsiString inspringen_2 = "                ";
   AnsiString inspringen_3 = "                        ";
   AnsiString inspringen_4 = "                                ";
   AnsiString xml_selected_date_report_preparation = "";        // hulp om DDMMYYY om te zetten naar YYYYMMDD
   AnsiString xml_selected_recruitment_vos = "";                // hulp om DDMMYYY om te zetten naar YYYYMMDD
   AnsiString xml_selected_derecruitment_vos = "";              // hulp om DDMMYYY om te zetten naar YYYYMMDD
   AnsiString xml_selected_recruitment_vosclim = "";            // hulp om DDMMYYY om te zetten naar YYYYMMDD
   AnsiString xml_selected_derecruitment_vosclim = "";          // hulp om DDMMYYY om te zetten naar YYYYMMDD
   AnsiString xml_selected_calibration_date_barometer_1 = "";   // hulp om DDMMYYY om te zetten naar YYYYMMDD
   AnsiString xml_selected_calibration_date_barometer_2 = "";   // hulp om DDMMYYY om te zetten naar YYYYMMDD
   AnsiString xml_selected_calibration_date_anemometer_1 = "";  // hulp om DDMMYYY om te zetten naar YYYYMMDD
   AnsiString xml_selected_calibration_date_anemometer_2 = "";  // hulp om DDMMYYY om te zetten naar YYYYMMDD
   AnsiString xml_selected_last_change_edit = "";               // hulp om DDMMYYY om te zetten naar YYYYMMDD


   /* xml output file openen */
   volledig_xml_output_path = metpub47_root_path + (AnsiString)output_sub_dir + "pub47_" + selected_imo_number + "_" + selected_call_sign + ".xml";

   of_xml.open(volledig_xml_output_path.c_str(), ios::out);
   if (of_xml)
   {
      // NB os.write kan ook

      /* <?xml version="1.0" encoding="utf-8" standalone="yes"?> */
      xml_regel = "";
      xml_regel = "<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\"?>";
      of_xml << xml_regel << '\n'; //endl;      // endl inserts the end of line character and flushes the output.

      /* <!-- Generated by Softsilver Transformer 2.5 (http://www.softsilver.com) --> */
      xml_regel = "";
      if (program_mode == UTILITY)
         xml_regel = "<!-- Generated by the TurboWin add-on MetPub47 --> ";
      else // stand-alone program
         xml_regel = "<!-- Generated by MetPub47 --> ";
      of_xml << xml_regel << '\n';

      /* <pub47dataset country="AU" version="03" prepared="20040920" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.bom.gov.au/jcomm/vos/pub47/pub47.xsd">*/
      xml_selected_date_report_preparation = selected_date_report_preparation.SubString(5, 4);
      xml_selected_date_report_preparation += selected_date_report_preparation.SubString(3, 2);
      xml_selected_date_report_preparation += selected_date_report_preparation.SubString(1, 2);
      xml_regel = "";
      xml_regel = "<pub47dataset country=\"";
      xml_regel += selected_recruiting_country_code;
      xml_regel += "\" version=\"";
      xml_regel += selected_version_pub47;
      xml_regel += "\" prepared=\"";
      xml_regel += xml_selected_date_report_preparation;
      xml_regel += "\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:noNamespaceSchemaLocation=\"http://www.bom.gov.au/jcomm/vos/pub47/pub47.xsd\">";
      of_xml << xml_regel << '\n';

      /* 	<pub47record nmsID="400002"> */
      xml_regel = "";
      xml_regel = inspringen_1;
      xml_regel += "<pub47record nmsID=\"";
      xml_regel += selected_nms_reference_number;
      xml_regel += "\">";
      of_xml << xml_regel << '\n';

      /* 		<name>AL KUWAIT</name> */
      xml_regel = "";
      xml_regel = inspringen_2;
      if (selected_ship_name != "")
      {
         xml_regel += "<name>";
         xml_regel += selected_ship_name.UpperCase();  // MOET DIT IN HOOFDLETTERS (en gaat het goed als er cijfers in de scheeps naam staan?
         xml_regel += "</name>";
      }
      else
      {
         xml_regel += "<name/>";
      }
      of_xml << xml_regel << '\n';

      /* 		<reg>KW</reg> */
      xml_regel = "";
      xml_regel = inspringen_2;
      if(selected_registration_country_code != "")
      {
         xml_regel += "<reg>";
         xml_regel += selected_registration_country_code;
         xml_regel += "</reg>";
      }
      else
      {
         xml_regel += "<reg/>";
      }   
      of_xml << xml_regel << '\n';

      /* 		<call>9KKS</call> */
      xml_regel = "";
      xml_regel = inspringen_2;
      if (selected_call_sign != "")
      {
         xml_regel += "<call>";
         xml_regel += selected_call_sign;
         xml_regel += "</call>";
      }
      else
      {
         xml_regel += "<call/>";
      }
      of_xml << xml_regel << '\n';

      /* 		<IMOn>6705303</IMOn> */
      xml_regel = "";
      xml_regel = inspringen_2;
      if (selected_imo_number != "")
      {
         xml_regel += "<IMOn>";
         xml_regel += selected_imo_number;
         xml_regel += "</IMOn>";
      }
      else
      {
         xml_regel += "<IMOn/>";
      }
      of_xml << xml_regel << '\n';

      /* 		<vssl footnote="">LC</vssl> */
      xml_regel = "";
      xml_regel = inspringen_2;
      if (selected_vessel_type_code != "")
      {
         xml_regel += "<vssl footnote=\"";
         xml_regel += selected_vessel_type_footnote;
         xml_regel += "\">";
         xml_regel += selected_vessel_type_code;
         xml_regel += "</vssl>";
      }
      else
      {
          xml_regel += "<vssl footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /*		<digital_image> */  
      xml_regel = "";
      xml_regel = inspringen_2;
      xml_regel += "<digital_image>";
      of_xml << xml_regel << '\n';

      /* 			<vsslP>AV</vsslP> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_digital_image_code != "")
      {
         xml_regel += "<vsslP>";
         xml_regel += selected_digital_image_code;
         xml_regel += "</vsslP>";
      }
      else
      {
         xml_regel += "<vsslP/>";
      }
      of_xml << xml_regel << '\n';

      /* 		</digital_image> */
      xml_regel = "";
      xml_regel = inspringen_2;
      xml_regel += "</digital_image>";
      of_xml << xml_regel << '\n';

      /* 		<dimensions> */
      xml_regel = "";
      xml_regel = inspringen_2;
      xml_regel += "<dimensions>";
      of_xml << xml_regel << '\n';

      /* 			<lenvsslD>195.0</lenvsslD> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_length != "")
      {
         xml_regel += "<lenvsslD>";
         xml_regel += selected_length;
         xml_regel += "</lenvsslD>";
      }
      else
      {
         xml_regel += "<lenvsslD/>";
      }
      of_xml << xml_regel << '\n';

      /* 			<brdvsslD>37.1</brdvsslD> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_breadth != "")
      {
         xml_regel += "<brdvsslD>";
         xml_regel += selected_breadth;
         xml_regel += "</brdvsslD>";
      }
      else
      {
         xml_regel += "<brdvsslD/>";
      }
      of_xml << xml_regel << '\n';

      /* 			<frbvsslD>17.8</frbvsslD> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_freeboard != "")
      {
         xml_regel += "<frbvsslD>";
         xml_regel += selected_freeboard;
         xml_regel += "</frbvsslD>";
      }
      else
      {
         xml_regel += "<frbvsslD/>";
      }
      of_xml << xml_regel << '\n';

      /* 			<drfvsslD>9.0</drfvsslD> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_draught != "")
      {
         xml_regel += "<drfvsslD>";
         xml_regel += selected_draught;
         xml_regel += "</drfvsslD>";
      }
      else
      {
         xml_regel += "<drfvsslD/>";
      }
      of_xml << xml_regel << '\n';

      /* 			<chtvsslD>19.0</chtvsslD> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_cargo_height != "")
      {
         xml_regel += "<chtvsslD>";
         xml_regel += selected_cargo_height;
         xml_regel += "</chtvsslD>";
      }
      else
      {
         xml_regel += "<chtvsslD/>";
      }
      of_xml << xml_regel << '\n';

      /* 			<brdg>32.0</brdg> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_bridge_bow != "")
      {
         xml_regel += "<brdg>";
         xml_regel += selected_bridge_bow;
         xml_regel += "</brdg>";
      }
      else
      {
         xml_regel += "<brdg/>";
      }
      of_xml << xml_regel << '\n';

      /* 		</dimensions> */
      xml_regel = "";
      xml_regel = inspringen_2;
      xml_regel += "</dimensions>";
      of_xml << xml_regel << '\n';

      /* 		<operations> */
      xml_regel = "";
      xml_regel = inspringen_2;
      xml_regel += "<operations>";
      of_xml << xml_regel << '\n';

      /* 			<rte Id="1" footnote="">10</rte> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_route_code_1 != "")
      {
         xml_regel += "<rte Id=\"1\" footnote=\"";
         xml_regel += selected_route_1_footnote;
         xml_regel += "\">";
         xml_regel += selected_route_code_1;
         xml_regel += "</rte>";
      }
      else
      {
         xml_regel += "<rte Id=\"1\" footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';
      
      /* 			<rte Id="2" footnote=""/> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_route_code_2 != "")
      {
         xml_regel += "<rte Id=\"2\" footnote=\"";
         xml_regel += selected_route_2_footnote;
         xml_regel += "\">";
         xml_regel += selected_route_code_2;
         xml_regel += "</rte>";
      }
      else
      {
         xml_regel += "<rte Id=\"2\" footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /* 			<rte Id="3" footnote=""/> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_route_code_3 != "")
      {
         xml_regel += "<rte Id=\"3\" footnote=\"";
         xml_regel += selected_route_3_footnote;
         xml_regel += "\">";
         xml_regel += selected_route_code_3;
         xml_regel += "</rte>";
      }
      else
      {
         xml_regel += "<rte Id=\"3\" footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /* 			<rte Id="4" footnote=""/> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_route_code_4 != "")
      {
         xml_regel += "<rte Id=\"4\" footnote=\"";
         xml_regel += selected_route_4_footnote;
         xml_regel += "\">";
         xml_regel += selected_route_code_4;
         xml_regel += "</rte>";
      }
      else
      {
         xml_regel += "<rte Id=\"4\" footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /* 			<rte Id="5" footnote=""/> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_route_code_5 != "")
      {
         xml_regel += "<rte Id=\"5\" footnote=\"";
         xml_regel += selected_route_5_footnote;
         xml_regel += "\">";
         xml_regel += selected_route_code_5;
         xml_regel += "</rte>";
      }
      else
      {
         xml_regel += "<rte Id=\"5\" footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /* 			<rte Id="6" footnote=""/> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_route_code_6 != "")
      {
         xml_regel += "<rte Id=\"6\" footnote=\"";
         xml_regel += selected_route_6_footnote;
         xml_regel += "\">";
         xml_regel += selected_route_code_6;
         xml_regel += "</rte>";
      }
      else
      {
         xml_regel += "<rte Id=\"6\" footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /* 			<rte Id="7" footnote=""/> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_route_code_7 != "")
      {
         xml_regel += "<rte Id=\"7\" footnote=\"";
         xml_regel += selected_route_7_footnote;
         xml_regel += "\">";
         xml_regel += selected_route_code_7;
         xml_regel += "</rte>";
      }
      else
      {
         xml_regel += "<rte Id=\"7\" footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /* 			<rte Id="8" footnote=""/> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_route_code_8 != "")
      {
         xml_regel += "<rte Id=\"8\" footnote=\"";
         xml_regel += selected_route_8_footnote;
         xml_regel += "\">";
         xml_regel += selected_route_code_8;
         xml_regel += "</rte>";
      }
      else
      {
         xml_regel += "<rte Id=\"8\" footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /* 			<rte Id="9" footnote=""/> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_route_code_9 != "")
      {
         xml_regel += "<rte Id=\"9\" footnote=\"";
         xml_regel += selected_route_9_footnote;
         xml_regel += "\">";
         xml_regel += selected_route_code_9;
         xml_regel += "</rte>";
      }
      else
      {
         xml_regel += "<rte Id=\"9\" footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /* 			<rte Id="10" footnote=""/> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_route_code_10 != "")
      {
         xml_regel += "<rte Id=\"10\" footnote=\"";
         xml_regel += selected_route_10_footnote;
         xml_regel += "\">";
         xml_regel += selected_route_code_10;
         xml_regel += "</rte>";
      }
      else
      {
         xml_regel += "<rte Id=\"10\" footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /* 		</operations> */
      xml_regel = "";
      xml_regel = inspringen_2;
      xml_regel += "</operations>";
      of_xml << xml_regel << '\n';

      /* 		<vos_service> */
      xml_regel = "";
      xml_regel = inspringen_2;
      xml_regel += "<vos_service>";
      of_xml << xml_regel << '\n';

      /*			<vosR>19920725</vosR> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_recruitment_vos != "")
      {
         xml_regel += "<vosR>";

         /* DDMMYYY omzetten naar YYYYMMDD */
         xml_selected_recruitment_vos = selected_recruitment_vos.SubString(5, 4);
         xml_selected_recruitment_vos += selected_recruitment_vos.SubString(3, 2);
         xml_selected_recruitment_vos += selected_recruitment_vos.SubString(1, 2);

         xml_regel += xml_selected_recruitment_vos;
         xml_regel += "</vosR>";
      }
      else
      {
         xml_regel += "<vosR/>";
      }
      of_xml << xml_regel << '\n';

      /* 			<vosD/> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_derecruitment_vos != "")
      {
         xml_regel += "<vosD>";

         /* DDMMYYY omzetten naar YYYYMMDD */
         xml_selected_derecruitment_vos = selected_derecruitment_vos.SubString(5, 4);
         xml_selected_derecruitment_vos += selected_derecruitment_vos.SubString(3, 2);
         xml_selected_derecruitment_vos += selected_derecruitment_vos.SubString(1, 2);

         xml_regel += xml_selected_derecruitment_vos;
         xml_regel += "</vosD>";
      }
      else
      {
         xml_regel += "<vosD/>";
      }
      of_xml << xml_regel << '\n';

      /* 			<vclmR/> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_recruitment_vosclim != "")
      {
         xml_regel += "<vclmR>";

         /* DDMMYYY omzetten naar YYYYMMDD */
         xml_selected_recruitment_vosclim = selected_recruitment_vosclim.SubString(5, 4);
         xml_selected_recruitment_vosclim += selected_recruitment_vosclim.SubString(3, 2);
         xml_selected_recruitment_vosclim += selected_recruitment_vosclim.SubString(1, 2);

         xml_regel += xml_selected_recruitment_vosclim;
         xml_regel += "</vclmR>";
      }
      else
      {
         xml_regel += "<vclmR/>";
      }
      of_xml << xml_regel << '\n';

      /* 			<vclmD/> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_derecruitment_vosclim != "")
      {
         xml_regel += "<vclmD>";

         /* DDMMYYY omzetten naar YYYYMMDD */
         xml_selected_derecruitment_vosclim = selected_derecruitment_vosclim.SubString(5, 4);
         xml_selected_derecruitment_vosclim += selected_derecruitment_vosclim.SubString(3, 2);
         xml_selected_derecruitment_vosclim += selected_derecruitment_vosclim.SubString(1, 2);

         xml_regel += xml_selected_derecruitment_vosclim;
         xml_regel += "</vclmD>";
      }
      else
      {
         xml_regel += "<vclmD/>";
      }
      of_xml << xml_regel << '\n';

      /* 		</vos_service> */
      xml_regel = "";
      xml_regel = inspringen_2;
      xml_regel += "</vos_service>";
      of_xml << xml_regel << '\n';

      /* 		<met_prgm> */
      xml_regel = "";
      xml_regel = inspringen_2;
      xml_regel += "<met_prgm>";
      of_xml << xml_regel << '\n';

      /* 			<vsslM footnote="">10</vsslM> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_type_meteo_ship_code != "")
      {
         xml_regel += "<vsslM footnote=\"";
         xml_regel += selected_footnote_type_meteo_ship;
         xml_regel += "\">";
         xml_regel += selected_type_meteo_ship_code;
         xml_regel += "</vsslM>";
      }
      else
      {
         xml_regel += "<vsslM footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /* 			<atm footnote="">5</atm> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_observing_practice_code != "")
      {
         xml_regel += "<atm footnote=\"";
         xml_regel += selected_footnote_selected_observing_practice;
         xml_regel += "\">";
         xml_regel += selected_observing_practice_code;
         xml_regel += "</atm>";
      }
      else
      {
          xml_regel += "<atm footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /* 			<freq footnote="">FPD</freq> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_observing_frequency_code != "")
      {
         xml_regel += "<freq footnote=\"";
         xml_regel += selected_footnote_observing_frequency;
         xml_regel += "\">";
         xml_regel += selected_observing_frequency_code;
         xml_regel += "</freq>";
      }
      else
      {
         xml_regel += "<freq footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /* 			<prST>CT41</prST> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_satellite_system_code != "")
      {
         xml_regel += "<prST>";
         xml_regel += selected_satellite_system_code;
         xml_regel += "</prST>";
      }
      else
      {
         xml_regel += "<prST/>";
      }
      of_xml << xml_regel << '\n';

      /* 			<logE/> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_electronic_logbook != "")
      {
         xml_regel += "<logE>";
         xml_regel += selected_electronic_logbook;
         xml_regel += "</logE>";
      }
      else
      {
         xml_regel += "<logE/>";
      }
      of_xml << xml_regel << '\n';

      /* 			<wwH/> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_wind_wave_height != "")
      {
         xml_regel += "<wwH>";
         xml_regel += selected_wind_wave_height;
         xml_regel += "</wwH>";
      }
      else
      {
         xml_regel += "<wwH/>";
      }
      of_xml << xml_regel << '\n';

      /*			<anmU footnote="">3</anmU> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_wind_practice_code != "")
      {
         xml_regel += "<anmU footnote=\"";
         xml_regel += selected_footnote_wind_practice;
         xml_regel += "\">";
         xml_regel += selected_wind_practice_code;
         xml_regel += "</anmU>";
      }
      else
      {
         xml_regel += "<anmU footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /* 			<blc footnote="">3</blc> */
      xml_regel = "";
      xml_regel = inspringen_3;
      if (selected_baseline_check_code != "")
      {
         xml_regel += "<blc footnote=\"";
         xml_regel += selected_footnote_baseline_check;
         xml_regel += "\">";
         xml_regel += selected_baseline_check_code;
         xml_regel += "</blc>";
      }
      else
      {
         xml_regel += "<blc footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /* 		</met_prgm> */
      xml_regel = "";
      xml_regel = inspringen_2;
      xml_regel += "</met_prgm>";
      of_xml << xml_regel << '\n';

      /* 		<instrumentation> */
      xml_regel = "";
      xml_regel = inspringen_2;
      xml_regel += "<instrumentation>";
      of_xml << xml_regel << '\n';

      /* 			<automated Id="1"> */
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "<automated Id=\"1\">";
      of_xml << xml_regel << '\n';

      /* 				<awsM/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_make_model_aws != "")
      {
         xml_regel += "<awsM>";
         xml_regel += selected_make_model_aws;
         xml_regel += "</awsM>";
      }
      else
      {
         xml_regel += "<awsM/>";
      }
      of_xml << xml_regel << '\n';

      /* 				<awsP/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_name_version_aws_processing_software != "")
      {
         xml_regel += "<awsP>";
         xml_regel += selected_name_version_aws_processing_software;
         xml_regel += "</awsP>";
      }
      else
      {
         xml_regel += "<awsP/>";
      }
      of_xml << xml_regel << '\n';

      /* 				<awsC/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_name_version_aws_display_software != "")
      {
         xml_regel += "<awsC>";
         xml_regel += selected_name_version_aws_display_software;
         xml_regel += "</awsC>";
      }
      else
      {
         xml_regel += "<awsC/>";
      }
      of_xml << xml_regel << '\n';

      /* 			</automated> */
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "</automated>";
      of_xml << xml_regel << '\n';

      /* 			<barometer Id="1"> */
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "<barometer Id=\"1\">";
      of_xml << xml_regel << '\n';

      /* 				<barm footnote="">DA</barm> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_barometer_type_code_1 != "")
      {
         xml_regel += "<barm footnote=\"";
         xml_regel += selected_footnote_barometer_1_type;
         xml_regel += "\">";
         xml_regel += selected_barometer_type_code_1;
         xml_regel += "</barm>";
      }
      else
      {
          xml_regel += "<barm footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /* 				<bMS/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_make_barometer_1 != "")
      {
         xml_regel += "<bMS>";
         xml_regel += selected_make_barometer_1;
         xml_regel += "</bMS>";
      }
      else
      {
         xml_regel += "<bMS/>";
      }
      of_xml << xml_regel << '\n';

      /* 				<brmH>12.0</brmH> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_height_barometer_1 != "")
      {
         xml_regel += "<brmH>";
         xml_regel += selected_height_barometer_1;
         xml_regel += "</brmH>";
      }
      else
      {
         xml_regel += "<brmH/>";
      }
      of_xml << xml_regel << '\n';

      /* 				<brmL footnote=""/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_barometer_location_code_1 != "")
      {
         xml_regel += "<brmL footnote=\"";
         xml_regel += selected_footnote_barometer_1_location;
         xml_regel += "\">";
         xml_regel += selected_barometer_location_code_1;
         xml_regel += "</brmL>";
      }
      else
      {
         xml_regel += "<brmL footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /*				<brmU/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_units_barometer_1 != "")
      {
         xml_regel += "<brmU>";
         xml_regel += selected_units_barometer_1;
         xml_regel += "</brmU>";
      }
      else
      {
         xml_regel += "<brmU/>";
      }
      of_xml << xml_regel << '\n';

      /* 				<brmC>20030409</brmC> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_calibration_date_barometer_1 != "")
      {
         xml_regel += "<brmC>";

         /* DDMMYYY omzetten naar YYYYMMDD */
         xml_selected_calibration_date_barometer_1 = selected_calibration_date_barometer_1.SubString(5, 4);
         xml_selected_calibration_date_barometer_1 += selected_calibration_date_barometer_1.SubString(3, 2);
         xml_selected_calibration_date_barometer_1 += selected_calibration_date_barometer_1.SubString(1, 2);

         xml_regel += xml_selected_calibration_date_barometer_1;
         xml_regel += "</brmC>";
      }
      else
      {
         xml_regel += "<brmC/>";
      }
      of_xml << xml_regel << '\n';

      /* 			</barometer> */
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "</barometer>";
      of_xml << xml_regel << '\n';

      /* 			<barometer Id="2"> */
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "<barometer Id=\"2\">";
      of_xml << xml_regel << '\n';

      /* 				<barm footnote="">DA</barm> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_barometer_type_code_2 != "")
      {
         xml_regel += "<barm footnote=\"";
         xml_regel += selected_footnote_barometer_2_type;
         xml_regel += "\">";
         xml_regel += selected_barometer_type_code_2;
         xml_regel += "</barm>";
      }
      else
      {
          xml_regel += "<barm footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /* 				<bMS/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_make_barometer_2 != "")
      {
         xml_regel += "<bMS>";
         xml_regel += selected_make_barometer_2;
         xml_regel += "</bMS>";
      }
      else
      {
         xml_regel += "<bMS/>";
      }
      of_xml << xml_regel << '\n';

      /* 				<brmH>12.0</brmH> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_height_barometer_2 != "")
      {
         xml_regel += "<brmH>";
         xml_regel += selected_height_barometer_2;
         xml_regel += "</brmH>";
      }
      else
      {
         xml_regel += "<brmH/>";
      }
      of_xml << xml_regel << '\n';

      /* 				<brmL footnote=""/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_barometer_location_code_2 != "")
      {
         xml_regel += "<brmL footnote=\"";
         xml_regel += selected_footnote_barometer_2_location;
         xml_regel += "\">";
         xml_regel += selected_barometer_location_code_2;
         xml_regel += "</brmL>";
      }
      else
      {
         xml_regel += "<brmL footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /*				<brmU/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_units_barometer_2 != "")
      {
         xml_regel += "<brmU>";
         xml_regel += selected_units_barometer_2;
         xml_regel += "</brmU>";
      }
      else
      {
         xml_regel += "<brmU/>";
      }
      of_xml << xml_regel << '\n';

      /* 				<brmC>20030409</brmC> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_calibration_date_barometer_2 != "")
      {
         xml_regel += "<brmC>";

         /* DDMMYYY omzetten naar YYYYMMDD */
         xml_selected_calibration_date_barometer_2 = selected_calibration_date_barometer_2.SubString(5, 4);
         xml_selected_calibration_date_barometer_2 += selected_calibration_date_barometer_2.SubString(3, 2);
         xml_selected_calibration_date_barometer_2 += selected_calibration_date_barometer_2.SubString(1, 2);

         xml_regel += xml_selected_calibration_date_barometer_2;
         xml_regel += "</brmC>";
      }
      else
      {
         xml_regel += "<brmC/>";
      }
      of_xml << xml_regel << '\n';

      /* 			</barometer> */
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "</barometer>";
      of_xml << xml_regel << '\n';

      /*			<dry_bulb Id="1"> */
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "<dry_bulb Id=\"1\">";
      of_xml << xml_regel << '\n';

      /*				<thrm footnote="">MER</thrm> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_dry_bulb_type_code_1 != "")
      {
         xml_regel += "<thrm footnote=\"";
         xml_regel += selected_footnote_type_dry_bulb_1;
         xml_regel += "\">";
         xml_regel += selected_dry_bulb_type_code_1;
         xml_regel += "</thrm>";
      }
      else
      {
         xml_regel += "<thrm footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /*				<thMS/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_make_dry_bulb_1 != "")
      {
         xml_regel += "<thMS>";
         xml_regel += selected_make_dry_bulb_1;
         xml_regel += "</thMS>";
      }
      else
      {
         xml_regel += "<thMS/>";
      }
      of_xml << xml_regel << '\n';

      /* 				<thmE footnote="">S</thmE> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_dry_bulb_exposure_code_1 != "")
      {
         xml_regel += "<thmE footnote=\"";
         xml_regel += selected_footnote_exposure_dry_bulb_1;
         xml_regel += "\">";
         xml_regel += selected_dry_bulb_exposure_code_1;
         xml_regel += "</thmE>";
      }
      else
      {
         xml_regel += "<thmE footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /*				<thmL footnote=""/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_dry_bulb_location_code_1 != "")
      {
         xml_regel += "<thmL footnote=\"";
         xml_regel += selected_footnote_location_dry_bulb_1;
         xml_regel += "\">";
         xml_regel += selected_dry_bulb_location_code_1;
         xml_regel += "</thmL>";
      }
      else
      {
         xml_regel += "<thmL footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /* 				<thmH/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_height_dry_bulb_1 != "")
      {
         xml_regel += "<thmH>";
         xml_regel += selected_height_dry_bulb_1;
         xml_regel += "</thmH>";
      }
      else
      {
         xml_regel += "<thmH/>";
      }
      of_xml << xml_regel << '\n';

      /* 				<tscale footnote=""/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_dry_bulb_reporting_code_1 != "")
      {
         xml_regel += "<tscale footnote=\"";
         xml_regel += selected_footnote_reporting_dry_bulb_1;
         xml_regel += "\">";
         xml_regel += selected_dry_bulb_reporting_code_1;
         xml_regel += "</tscale>";
      }
      else
      {
         xml_regel += "<tscale footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /*			</dry_bulb> */
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "</dry_bulb>";
      of_xml << xml_regel << '\n';

      /*			<dry_bulb Id="2"> */
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "<dry_bulb Id=\"2\">";
      of_xml << xml_regel << '\n';

      /*				<thrm footnote="">MER</thrm> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_dry_bulb_type_code_2 != "")
      {
         xml_regel += "<thrm footnote=\"";
         xml_regel += selected_footnote_type_dry_bulb_2;
         xml_regel += "\">";
         xml_regel += selected_dry_bulb_type_code_2;
         xml_regel += "</thrm>";
      }
      else
      {
         xml_regel += "<thrm footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /*				<thMS/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_make_dry_bulb_2 != "")
      {
         xml_regel += "<thMS>";
         xml_regel += selected_make_dry_bulb_2;
         xml_regel += "</thMS>";
      }
      else
      {
         xml_regel += "<thMS/>";
      }
      of_xml << xml_regel << '\n';

      /* 				<thmE footnote="">S</thmE> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_dry_bulb_exposure_code_2 != "")
      {
         xml_regel += "<thmE footnote=\"";
         xml_regel += selected_footnote_exposure_dry_bulb_2;
         xml_regel += "\">";
         xml_regel += selected_dry_bulb_exposure_code_2;
         xml_regel += "</thmE>";
      }
      else
      {
         xml_regel += "<thmE footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /*				<thmL footnote=""/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_dry_bulb_location_code_2 != "")
      {
         xml_regel += "<thmL footnote=\"";
         xml_regel += selected_footnote_location_dry_bulb_2;
         xml_regel += "\">";
         xml_regel += selected_dry_bulb_location_code_2;
         xml_regel += "</thmL>";
      }
      else
      {
         xml_regel += "<thmL footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /* 				<thmH/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_height_dry_bulb_2 != "")
      {
         xml_regel += "<thmH>";
         xml_regel += selected_height_dry_bulb_2;
         xml_regel += "</thmH>";
      }
      else
      {
         xml_regel += "<thmH/>";
      }
      of_xml << xml_regel << '\n';

      /* 				<tscale footnote=""/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_dry_bulb_reporting_code_2 != "")
      {
         xml_regel += "<tscale footnote=\"";
         xml_regel += selected_footnote_reporting_dry_bulb_2;
         xml_regel += "\">";
         xml_regel += selected_dry_bulb_reporting_code_2;
         xml_regel += "</tscale>";
      }
      else
      {
         xml_regel += "<tscale footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /*			</dry_bulb> */
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "</dry_bulb>";
      of_xml << xml_regel << '\n';

      /*			<hygrometer Id="1"> */
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "<hygrometer Id=\"1\">";
      of_xml << xml_regel << '\n';

      /*				<hygr footnote="">P</hygr> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_hygrometer_type_code_1 != "")
      {
         xml_regel += "<hygr footnote=\"";
         xml_regel += selected_footnote_hygrometer_type_1;
         xml_regel += "\">";
         xml_regel += selected_hygrometer_type_code_1;
         xml_regel += "</hygr>";
      }
      else
      {
         xml_regel += "<hygr footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /*				<hgrE footnote="">S</hgrE> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_hygrometer_exposure_code_1 != "")
      {
         xml_regel += "<hgrE footnote=\"";
         xml_regel += selected_footnote_hygrometer_exposure_1;
         xml_regel += "\">";
         xml_regel += selected_hygrometer_exposure_code_1;
         xml_regel += "</hgrE>";
      }
      else
      {
         xml_regel += "<hgrE footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /*			</hygrometer> */
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "</hygrometer>";
      of_xml << xml_regel << '\n';

      /*			<hygrometer Id="2"> */
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "<hygrometer Id=\"2\">";
      of_xml << xml_regel << '\n';

      /*				<hygr footnote="">P</hygr> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_hygrometer_type_code_2 != "")
      {
         xml_regel += "<hygr footnote=\"";
         xml_regel += selected_footnote_hygrometer_type_2;
         xml_regel += "\">";
         xml_regel += selected_hygrometer_type_code_2;
         xml_regel += "</hygr>";
      }
      else
      {
         xml_regel += "<hygr footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /*				<hgrE footnote="">S</hgrE> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_hygrometer_exposure_code_2 != "")
      {
         xml_regel += "<hgrE footnote=\"";
         xml_regel += selected_footnote_hygrometer_exposure_2;
         xml_regel += "\">";
         xml_regel += selected_hygrometer_exposure_code_2;
         xml_regel += "</hgrE>";
      }
      else
      {
         xml_regel += "<hgrE footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /*			</hygrometer> */
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "</hygrometer>";
      of_xml << xml_regel << '\n';

      /*			<sea_temp Id="1"> */
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "<sea_temp Id=\"1\">";
      of_xml << xml_regel << '\n';

      /*				<sstM footnote="">BU</sstM> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_sst_method_code_1 != "")
      {
         xml_regel += "<sstM footnote=\"";
         xml_regel += selected_footnote_method_sst_1;
         xml_regel += "\">";
         xml_regel += selected_sst_method_code_1;
         xml_regel += "</sstM>";
      }
      else
      {
         xml_regel += "<sstM footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /*				<sstD/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_depth_sst_1 != "")
      {
         xml_regel += "<sstD>";
         xml_regel += selected_depth_sst_1;
         xml_regel += "</sstD>";
      }
      else
      {
         xml_regel += "<sstD/>";
      }
      of_xml << xml_regel << '\n';

      /* 			</sea_temp> */
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "</sea_temp>";
      of_xml << xml_regel << '\n';

      /*			<sea_temp Id="2"> */
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "<sea_temp Id=\"2\">";
      of_xml << xml_regel << '\n';

      /*				<sstM footnote="">BU</sstM> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_sst_method_code_2 != "")
      {
         xml_regel += "<sstM footnote=\"";
         xml_regel += selected_footnote_method_sst_2;
         xml_regel += "\">";
         xml_regel += selected_sst_method_code_2;
         xml_regel += "</sstM>";
      }
      else
      {
         xml_regel += "<sstM footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /*				<sstD/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_depth_sst_2 != "")
      {
         xml_regel += "<sstD>";
         xml_regel += selected_depth_sst_2;
         xml_regel += "</sstD>";
      }
      else
      {
         xml_regel += "<sstD/>";
      }
      of_xml << xml_regel << '\n';

      /* 			</sea_temp> */
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "</sea_temp>";
      of_xml << xml_regel << '\n';

      /*			<barograph Id="1"> */
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "<barograph Id=\"1\">";
      of_xml << xml_regel << '\n';

      /*				<barg footnote="">OS7</barg> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_barograph_type_code_1 != "")
      {
         xml_regel += "<barg footnote=\"";
         xml_regel += selected_footnote_type_barograph_1;
         xml_regel += "\">";
         xml_regel += selected_barograph_type_code_1;
         xml_regel += "</barg>";
      }
      else
      {
         xml_regel += "<barg footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /*			</barograph>*/
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "</barograph>";
      of_xml << xml_regel << '\n';

      /*			<barograph Id="1"> */
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "<barograph Id=\"2\">";
      of_xml << xml_regel << '\n';

      /*				<barg footnote="">OS7</barg> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_barograph_type_code_2 != "")
      {
         xml_regel += "<barg footnote=\"";
         xml_regel += selected_footnote_type_barograph_2;
         xml_regel += "\">";
         xml_regel += selected_barograph_type_code_2;
         xml_regel += "</barg>";
      }
      else
      {
         xml_regel += "<barg footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /*			</barograph>*/
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "</barograph>";
      of_xml << xml_regel << '\n';

      /*			<anemometer Id="1"> */
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "<anemometer Id=\"1\">";
      of_xml << xml_regel << '\n';

      /*				<anmT footnote=""/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_anemometer_type_code_1 != "")
      {
         xml_regel += "<anmT footnote=\"";
         xml_regel += selected_footnote_type_anemometer_1;
         xml_regel += "\">";
         xml_regel += selected_anemometer_type_code_1;
         xml_regel += "</anmT>";
      }
      else
      {
         xml_regel += "<anmT footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /*				<anmM/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_make_anemometer_1 != "")
      {
         xml_regel += "<anmM>";
         xml_regel += selected_make_anemometer_1;
         xml_regel += "</anmM>";
      }
      else
      {
         xml_regel += "<anmM/>";
      }
      of_xml << xml_regel << '\n';

      /*				<anmL footnote="">1</anmL> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_anemometer_location_code_1 != "")
      {
         xml_regel += "<anmL footnote=\"";
         xml_regel += selected_footnote_location_anemometer_1;
         xml_regel += "\">";
         xml_regel += selected_anemometer_location_code_1;
         xml_regel += "</anmL>";
      }
      else
      {
         xml_regel += "<anmL footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /*				<anDB/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_distance_bow_anemometer_1 != "")
      {
         xml_regel += "<anDB>";
         xml_regel += selected_distance_bow_anemometer_1;
         xml_regel += "</anDB>";
      }
      else
      {
         xml_regel += "<anDB/>";
      }
      of_xml << xml_regel << '\n';

      /*				<anDC/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_distance_centre_line_anemometer_1 != "")
      {
         xml_regel += "<anDC>";
         xml_regel += selected_distance_centre_line_anemometer_1;
         xml_regel += "</anDC>";
      }
      else
      {
         xml_regel += "<anDC/>";
      }
      of_xml << xml_regel << '\n';

      /*				<anSC/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_anemometer_sideindicator_code_1 != "")
      {
         xml_regel += "<anSC>";
         xml_regel += selected_anemometer_sideindicator_code_1;
         xml_regel += "</anSC>";
      }
      else
      {
         xml_regel += "<anSC/>";
      }
      of_xml << xml_regel << '\n';

      /*				<anHL/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_height_sll_anemometer_1 != "")
      {
         xml_regel += "<anHL>";
         xml_regel += selected_height_sll_anemometer_1;
         xml_regel += "</anHL>";
      }
      else
      {
         xml_regel += "<anHL/>";
      }
      of_xml << xml_regel << '\n';

      /* 				<anHD/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_height_deck_anemometer_1 != "")
      {
         xml_regel += "<anHD>";
         xml_regel += selected_height_deck_anemometer_1;
         xml_regel += "</anHD>";
      }
      else
      {
         xml_regel += "<anHD/>";
      }
      of_xml << xml_regel << '\n';

      /*				<anmC/> */
      xml_regel = "";
      xml_regel = inspringen_4;


      if (selected_calibration_date_anemometer_1 != "")
      {
         xml_regel += "<anmC>";

         /* DDMMYYY omzetten naar YYYYMMDD */
         xml_selected_calibration_date_anemometer_1 = selected_calibration_date_anemometer_1.SubString(5, 4);
         xml_selected_calibration_date_anemometer_1 += selected_calibration_date_anemometer_1.SubString(3, 2);
         xml_selected_calibration_date_anemometer_1 += selected_calibration_date_anemometer_1.SubString(1, 2);

         xml_regel += xml_selected_calibration_date_anemometer_1;
         xml_regel += "</anmC>";
      }
      else
      {
         xml_regel += "<anmC/>";
      }
      of_xml << xml_regel << '\n';

      /*			</anemometer> */
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "</anemometer>";
      of_xml << xml_regel << '\n';

      /*			<anemometer Id="2"> */
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "<anemometer Id=\"2\">";
      of_xml << xml_regel << '\n';

      /*				<anmT footnote=""/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_anemometer_type_code_2 != "")
      {
         xml_regel += "<anmT footnote=\"";
         xml_regel += selected_footnote_type_anemometer_2;
         xml_regel += "\">";
         xml_regel += selected_anemometer_type_code_2;
         xml_regel += "</anmT>";
      }
      else
      {
         xml_regel += "<anmT footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /*				<anmM/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_make_anemometer_2 != "")
      {
         xml_regel += "<anmM>";
         xml_regel += selected_make_anemometer_2;
         xml_regel += "</anmM>";
      }
      else
      {
         xml_regel += "<anmM/>";
      }
      of_xml << xml_regel << '\n';

      /*				<anmL footnote="">1</anmL> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_anemometer_location_code_2 != "")
      {
         xml_regel += "<anmL footnote=\"";
         xml_regel += selected_footnote_location_anemometer_2;
         xml_regel += "\">";
         xml_regel += selected_anemometer_location_code_2;
         xml_regel += "</anmL>";
      }
      else
      {
         xml_regel += "<anmL footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /*				<anDB/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_distance_bow_anemometer_2 != "")
      {
         xml_regel += "<anDB>";
         xml_regel += selected_distance_bow_anemometer_2;
         xml_regel += "</anDB>";
      }
      else
      {
         xml_regel += "<anDB/>";
      }
      of_xml << xml_regel << '\n';

      /*				<anDC/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_distance_centre_line_anemometer_2 != "")
      {
         xml_regel += "<anDC>";
         xml_regel += selected_distance_centre_line_anemometer_2;
         xml_regel += "</anDC>";
      }
      else
      {
         xml_regel += "<anDC/>";
      }
      of_xml << xml_regel << '\n';

      /*				<anSC/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_anemometer_sideindicator_code_2 != "")
      {
         xml_regel += "<anSC>";
         xml_regel += selected_anemometer_sideindicator_code_2;
         xml_regel += "</anSC>";
      }
      else
      {
         xml_regel += "<anSC/>";
      }
      of_xml << xml_regel << '\n';

      /*				<anHL/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_height_sll_anemometer_2 != "")
      {
         xml_regel += "<anHL>";
         xml_regel += selected_height_sll_anemometer_2;
         xml_regel += "</anHL>";
      }
      else
      {
         xml_regel += "<anHL/>";
      }
      of_xml << xml_regel << '\n';

      /* 				<anHD/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_height_deck_anemometer_2 != "")
      {
         xml_regel += "<anHD>";
         xml_regel += selected_height_deck_anemometer_2;
         xml_regel += "</anHD>";
      }
      else
      {
         xml_regel += "<anHD/>";
      }
      of_xml << xml_regel << '\n';

      /*				<anmC/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_calibration_date_anemometer_2 != "")
      {
         xml_regel += "<anmC>";

        /* DDMMYYY omzetten naar YYYYMMDD */
         xml_selected_calibration_date_anemometer_2 = selected_calibration_date_anemometer_2.SubString(5, 4);
         xml_selected_calibration_date_anemometer_2 += selected_calibration_date_anemometer_2.SubString(3, 2);
         xml_selected_calibration_date_anemometer_2 += selected_calibration_date_anemometer_2.SubString(1, 2);

         xml_regel += xml_selected_calibration_date_anemometer_2;
         xml_regel += "</anmC>";
      }
      else
      {
         xml_regel += "<anmC/>";
      }
      of_xml << xml_regel << '\n';

      /*			</anemometer> */
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "</anemometer>";
      of_xml << xml_regel << '\n';

      /*			<other> */
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "<other>";
      of_xml << xml_regel << '\n';

      /*				<othI Id="1" footnote=""/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_other_instrument_code_1 != "")
      {
         xml_regel += "<othI Id=\"1\" footnote=\"";
         xml_regel += selected_footnote_other_instrument_1;
         xml_regel += "\">";
         xml_regel += selected_other_instrument_code_1;
         xml_regel += "</othI>";
      }
      else
      {
         xml_regel += "<othI Id=\"1\" footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /*				<othI Id="2" footnote=""/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_other_instrument_code_2 != "")
      {
         xml_regel += "<othI Id=\"2\" footnote=\"";
         xml_regel += selected_footnote_other_instrument_2;
         xml_regel += "\">";
         xml_regel += selected_other_instrument_code_2;
         xml_regel += "</othI>";
      }
      else
      {
         xml_regel += "<othI Id=\"2\" footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /*				<othI Id="3" footnote=""/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_other_instrument_code_3 != "")
      {
         xml_regel += "<othI Id=\"3\" footnote=\"";
         xml_regel += selected_footnote_other_instrument_3;
         xml_regel += "\">";
         xml_regel += selected_other_instrument_code_3;
         xml_regel += "</othI>";
      }
      else
      {
         xml_regel += "<othI Id=\"3\" footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /*				<othI Id="4" footnote=""/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_other_instrument_code_4 != "")
      {
         xml_regel += "<othI Id=\"4\" footnote=\"";
         xml_regel += selected_footnote_other_instrument_4;
         xml_regel += "\">";
         xml_regel += selected_other_instrument_code_4;
         xml_regel += "</othI>";
      }
      else
      {
         xml_regel += "<othI Id=\"4\" footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /*				<othI Id="5" footnote=""/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_other_instrument_code_5 != "")
      {
         xml_regel += "<othI Id=\"5\" footnote=\"";
         xml_regel += selected_footnote_other_instrument_5;
         xml_regel += "\">";
         xml_regel += selected_other_instrument_code_5;
         xml_regel += "</othI>";
      }
      else
      {
         xml_regel += "<othI Id=\"5\" footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /*				<othI Id="6" footnote=""/> */
      xml_regel = "";
      xml_regel = inspringen_4;
      if (selected_other_instrument_code_6 != "")
      {
         xml_regel += "<othI Id=\"6\" footnote=\"";
         xml_regel += selected_footnote_other_instrument_6;
         xml_regel += "\">";
         xml_regel += selected_other_instrument_code_6;
         xml_regel += "</othI>";
      }
      else
      {
         xml_regel += "<othI Id=\"6\" footnote=\"\"/>";
      }
      of_xml << xml_regel << '\n';

      /* 			</other> */
      xml_regel = "";
      xml_regel = inspringen_3;
      xml_regel += "</other>";
      of_xml << xml_regel << '\n';

      /* 		</instrumentation> */
      xml_regel = "";
      xml_regel = inspringen_2;
      xml_regel += "</instrumentation>";
      of_xml << xml_regel << '\n';

      /*		<chgd>20040219</chgd> */
      xml_regel = "";
      xml_regel = inspringen_2;
      if (selected_last_change_edit != "")
      {
         xml_regel += "<chgd>";

         /* DDMMYYY omzetten naar YYYYMMDD */
         xml_selected_last_change_edit = selected_last_change_edit.SubString(5, 4);
         xml_selected_last_change_edit += selected_last_change_edit.SubString(3, 2);
         xml_selected_last_change_edit += selected_last_change_edit.SubString(1, 2);

         xml_regel += xml_selected_last_change_edit;
         xml_regel += "</chgd>";
      }
      else
      {
         xml_regel += "<chgd/>";
      }
      of_xml << xml_regel << '\n';

      /*	</pub47record> */
      xml_regel = "";
      xml_regel = inspringen_1;
      xml_regel += "</pub47record>";
      of_xml << xml_regel << '\n';

      /* </pub47dataset> */
      xml_regel = "";
      xml_regel += "</pub47dataset>";
      of_xml << xml_regel << '\n';


      of_xml.close();

   }  // if (of_xml)
   else // dus .xml niet te schrijven
   {
      schrijven_ok = false;

      info = "Unable to write to: ";
      info += volledig_xml_output_path;
      MessageBox(0, info.c_str(), program_name" error", MB_OK | MB_ICONWARNING);
   } // else (dus .xml niet te schrijven)


   return schrijven_ok;
}
